### ISSUE TITLE
Нужно использовать компонент

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/react#1]
По заданию нужно использовать компонент для вывода данных о блюде

https://github.com/aldarsemenov/react/blob/fe134e97c560b36c77c69d3616ccd4770e6a8c9b/src/App.js#L59

**Comment by aldarsemenov** [comment]
стили же не обязательно сейчас применять?) пока без них сделал.

**Comment by aldarsemenov** [comment]
еще мышку купил которую советовал) по блютузу и шума нет от нее))

**Comment by uzarsalan** [comment]
> стили же не обязательно сейчас применять?) пока без них сделал.

Да, сейчас не обязательно
