### ISSUE TITLE
Папка с компонентом menu с маленькой буквы

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/react#3]
Название папки написано с маленькой буквы, из-за этого ошибка

<img width="690" alt="image" src="https://user-images.githubusercontent.com/16972594/235377124-a9999cb5-3f35-4d7a-90be-d8a4315b4555.png">

**Comment by aldarsemenov** [comment]
Прикол что у меня в проекте с большой. Скрин отправил в дз на уроке
