### ISSUE TITLE
Соблюдение стандартов в написании

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/react#5]
В написании соблюдай стандарт. В camelCase каждое слово должно начинаться с большой буквы (AboutPage)

https://github.com/aldarsemenov/react/blob/ee05cc89f8cf78436f7d7a77a17e3855f7d927b1/src/router/index.js#L25

https://github.com/aldarsemenov/react/blob/ee05cc89f8cf78436f7d7a77a17e3855f7d927b1/src/components/Mainmenu/index.js#L3

Проверь везде

**Comment by aldarsemenov** [comment]
Вроде все исправил)
